---
title: "Dithwa Storm Impact: Weather Data Monitoring & Analysis Dashboard"
subtitle: "Note: Read ABOUT panel to see the description"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(flexdashboard)
library(tidyverse)
library(Ditwah)
library(plotly)
data(weather_report)
```

# Meteorological Station

```{r, fig.width=20}
weather_order <-
  weather_report |>
  filter(Type == "Meteorological Station",
         Reporting_Time == "for the 24 hour period ending at 0830SLTS on 28-11-2025") |>
  mutate(Daily_Rainfall_mm = as.numeric(Daily_Rainfall_mm)) |>
  arrange(desc(Daily_Rainfall_mm)) |>
  pull(Name)

p1 <- weather_report |>
  filter(Type == "Meteorological Station") |>
  mutate(
    Daily_Rainfall_mm = as.numeric(Daily_Rainfall_mm),
    Name = factor(Name, levels = weather_order)   # <-- Reordered here
  ) |>
  ggplot(aes(
    x = Name,
    y = Daily_Rainfall_mm,
    fill = Reporting_Time
  )) +
  geom_col(position = "dodge", width = 0.7) +
  scale_fill_manual(values = c("#d95f02", "#1b9e77")) +
  labs(
    title = "Comparison of Daily Rainfall: 28 Nov 2025 vs 29 Nov 2025",
    x = "Meteorological Station",
    y = "Rainfall (mm)",
    fill = "Reporting Time"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "bottom"
  )

p1
ggplotly(p1)

```
# Meteorological Station

```{r, fig.width=20}
weather_order <-
  weather_report |>
  filter(Type == "Meteorological Station",
         Reporting_Time == "for the 24 hour period ending at 0830SLTS on 28-11-2025") |>
  mutate(Daily_Rainfall_mm = as.numeric(Daily_Rainfall_mm)) |>
  arrange(desc(Daily_Rainfall_mm)) |>
  pull(Name)

p1 <- weather_report |>
  filter(Type == "Meteorological Station") |>
  mutate(
    Daily_Rainfall_mm = as.numeric(Daily_Rainfall_mm),
    Name = factor(Name, levels = weather_order)   # <-- Reordered here
  ) |>
  ggplot(aes(
    x = Name,
    y = Daily_Rainfall_mm,
    fill = Reporting_Time
  )) +
  geom_col(position = "dodge", width = 0.7) +
  scale_fill_manual(values = c("#d95f02", "#1b9e77")) +
  labs(
    title = "Comparison of Daily Rainfall: 28 Nov 2025 vs 29 Nov 2025",
    x = "Meteorological Station",
    y = "Rainfall (mm)",
    fill = "Reporting Time"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "bottom"
  )

p1
ggplotly(p1)

```
